name: win_msvc_dbg_x64

on:
  push:
    paths:
      - 'src/**'
      - 'DEPS'

  pull_request:
    paths:
      - 'src/**'
      - 'DEPS'

jobs:

  win_msvc_dbg_x64:

    runs-on: windows-2019

    steps:
    - name: Git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Install depot_tools
      shell: cmd
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git ..\depot_tools
        set "PATH=%CD%\..\depot_tools;%PATH%"
        gclient

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: actions/checkout@v2
      with:
        path: test
        fetch-depth: 0

    - name: Sync code for main branch (with patch)
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd test
        copy scripts\standalone.gclient .gclient
        gclient sync

    - name: Generate shared library for main branch (with patch)
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd test
        gn gen out\Debug --args="is_debug=true is_clang=false gpgmm_shared_library=true"

    - name: Build shared library for main branch (with patch)
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd test
        ninja -C out\Debug gpgmm

    - name: Generate project for main branch (with patch)
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd test
        gn gen out\Debug --args="is_debug=true is_clang=false gpgmm_disable_size_cache=true"

    - name: Build for main branch (with patch)
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd test
        ninja -C out\Debug

    - name: Run gpgmm_end2end_tests (with patch)
      shell: cmd
      run: |
        cd test
        out\Debug\gpgmm_end2end_tests.exe 2>&1

    - name: Run gpgmm_unittests (with patch)
      shell: cmd
      run: |
        cd test
        out\Debug\gpgmm_unittests.exe

    - name: Run gpgmm_capture_replay_tests (with patch)
      shell: cmd
      run: |
        cd test
        out\Debug\gpgmm_capture_replay_tests.exe --log-level=DEBUG 2>&1
